# Generated by Django 5.1 on 2024-08-15 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='blogs'),
        ),
        migrations.AddField(
            model_name='posts',
            name='subtitle',
            field=models.CharField(default='This is a test', max_length=50),
        ),
    ]
