# Generated by Django 5.1 on 2024-08-16 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_posts_image_posts_subtitle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='subtitle',
            field=models.CharField(default='This is a test', max_length=250),
        ),
    ]
