# Generated by Django 5.1 on 2024-09-09 11:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 9, 11, 7, 1, 796046, tzinfo=datetime.timezone.utc)),
        ),
    ]
