# Generated by Django 5.1 on 2024-09-09 11:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_message_created'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['name', 'email', 'message', 'created']},
        ),
        migrations.RemoveIndex(
            model_name='message',
            name='blog_messag_first_n_2c652f_idx',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='message',
            name='last_name',
        ),
        migrations.AlterField(
            model_name='message',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 9, 11, 27, 59, 233742, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['name', 'message'], name='blog_messag_name_722e71_idx'),
        ),
    ]
