# Generated by Django 5.1 on 2024-09-10 00:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_message_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['name', 'last_name', 'email', 'message', 'created']},
        ),
        migrations.RemoveIndex(
            model_name='message',
            name='blog_messag_name_722e71_idx',
        ),
        migrations.AddField(
            model_name='message',
            name='last_name',
            field=models.CharField(default='Null', max_length=25),
        ),
        migrations.AlterField(
            model_name='message',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 10, 0, 44, 52, 793618, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['name', 'last_name', 'email', 'message'], name='blog_messag_name_4345eb_idx'),
        ),
    ]
