# Generated by Django 5.1 on 2024-09-10 03:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_message_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 10, 3, 6, 45, 262329, tzinfo=datetime.timezone.utc)),
        ),
    ]
